### ISSUE TITLE
Implementation of MSG_TYPE_STOP_REQUEST

### ISSUE THREAD

**Issue by hokeun** [lf-lang/reactor-ts#101]
Currently, federated TS does not support the [MSG_TYPE_STOP_REQUEST](https://github.com/lf-lang/reactor-c/blob/main/core/federated/net_common.h#L441) message.
We need to implement this so that we can stop the whole federation when a single federate requests stop.

**Comment by hokeun** [comment]
@lhstrh , do you think you could add @ByeongGil-Jun to reactor-ts as a member? He will be working on this with me, and I plan to have him work on other reactor-ts issues as the next tasks. It would be much easier if he's a member and he can push to the origin branches. Thanks!

**Comment by lhstrh** [comment]
@ByeongGil-Jun should have received an invitation.

**Comment by ByeongGil-Jun** [comment]
@hokeun @lhstrh I showed and accepted an invitation. Thank you

**Comment by ByeongGil-Jun** [comment]
@hokeun This is the line we talked about.
https://github.com/lf-lang/reactor-c/blob/e1e2bd3b16a3a450c266550ffe745170136fadf0/core/federated/net_common.h#L426

**Comment by hokeun** [comment]
This will be addressed by https://github.com/lf-lang/reactor-ts/pull/111 and https://github.com/lf-lang/lingua-franca/pull/1302.
