### ISSUE TITLE
NPM Packaging of reactor-ts

### ISSUE THREAD

**Issue by hokeun** [lf-lang/reactor-ts#104]
- Goal: Simplifying Lfc process by using installed npm instead of copying files of reactor-ts.

- Steps
1. Create an NPM account.
[https://www.npmjs.com/](https://www.npmjs.com/)

2. In the terminal, enter the command to login.
```
npm login
```
Enter your username, password and email ID.
If you want to check if you signed in correctly, you can check with this command. (Username will be printed)
```
npm whoami
```

3. Prepare `package.json` file and publish it.

```
npm publish
```
- Installing and testing the packages
```
mkdir [package-test folder] && cd [package-test folder]
npm init -y
npm i [packagename]
```
Create `index.js` file to use the packages and run this.
```
node index.js
```

- version check
```
npm version patch
```

- Unpublishing
If you want to unpublish the packages, you need to do it within 72 hours after you publish your packages, or you should contact to npm directly.
[https://docs.npmjs.com/unpublishing-packages-from-the-registry](https://docs.npmjs.com/unpublishing-packages-from-the-registry)

**Comment by suyourice** [comment]
@lhstrh I wrote some commands which are needed when making npm packages. Is there any more information to mention or are there more things to include in `pakcage.json`? I also want to ask you about the next step to do.

**Comment by lhstrh** [comment]
Thanks for leaving this instructions, @suyourice. The key thing that has to happen before publishing is testing locally. Here are some helpful tutorials about this:
 - https://www.jamesqquick.com/blog/how-to-test-npm-packages-locally
 - https://medium.com/@vcarl/problems-with-npm-link-and-an-alternative-4dbdd3e66811
 - https://javascript.plainenglish.io/how-to-test-a-node-package-locally-8dde33e642df

One problem that I anticipate is that we need to export a bunch of stuff. We use the pattern described [here](https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de) to avoid running into circular dependencies. All files import from a file called `internal.ts`, which, as the name suggests, is for internal use only. What's currently missing is an `index.ts` that exports all the things that we want to make accessible via our `reactor-ts` package.

**Comment by petervdonovan** [comment]
To add on to our conversation just now, I don't object to copying source files. Apparently, JavaScript developers do that all the time with `node_modules` and it works OK for them (disk space is cheap). I think the real advantage to packaging the runtime is that it makes it more modular and gives it a sane structure. Therefore, even if we were to continue copying the whole thing, I would be happy as long as the runtime files are properly packaged and pointed to in `package.json` like a regular dependency (instead of being directly imported into source files).

**Comment by lhstrh** [comment]
This has been finalized. The package is available here: https://www.npmjs.com/package/@lf-lang/reactor-ts
To (patch) bump reactor-ts:
```bash
npm version patch
git push --tags origin master
npm publish
```

There is currently no automated release triggered on GitHub, but we could change that at a later time.
