### ISSUE TITLE
physical connection handling in the federated execution

### ISSUE THREAD

**Issue by byeong-gil** [lf-lang/reactor-ts#143]
`reactor-ts` cannot handle physical connection currently.

A tagged message via the physical connection is scheduled in this code ([federation.ts#L1375](https://github.com/lf-lang/reactor-ts/blob/8d8ff4f22cd0321bb159eb9bd91759e87f6ed531/src/core/federation.ts#L1375)). However, this leads to an error at this line ([action.ts#L83](https://github.com/lf-lang/reactor-ts/blob/8d8ff4f22cd0321bb159eb9bd91759e87f6ed531/src/core/action.ts#L83)).

Thus, [DistributedCountPhysical.lf](https://github.com/lf-lang/lingua-franca/blob/ts-physical-conn-tests/test/TypeScript/src/federated/DistributedCountPhysical.lf) and [PingPongDistributedPhysical.lf](https://github.com/lf-lang/lingua-franca/blob/ts-physical-conn-tests/test/TypeScript/src/federated/PingPongDistributedPhysical.lf) are now failed.

**Comment by lhstrh** [comment]
Could it be that https://github.com/lf-lang/reactor-ts/blob/8d8ff4f22cd0321bb159eb9bd91759e87f6ed531/src/core/action.ts#L81 should be an `else if`?

**Comment by byeong-gil** [comment]
Can we make that line `else if` although the message from the physical connection is both `Origin.physical` and `FederatedPortAction`?
I mean, it enters both [action.ts#L81](https://github.com/lf-lang/reactor-ts/blob/8d8ff4f22cd0321bb159eb9bd91759e87f6ed531/src/core/action.ts#L81) and [action.ts#L83](https://github.com/lf-lang/reactor-ts/blob/8d8ff4f22cd0321bb159eb9bd91759e87f6ed531/src/core/action.ts#L83).

**Comment by lhstrh** [comment]
The checks done in the branch guarded by `this.action isntanceof FederatePortAction` concerns the "intended tag" which there is none if the the original connection is physical, right? Considering that, it seems the checks can be safely disregarded. Will the program work as expected with the suggested modification, or are there still problems?

**Comment by byeong-gil** [comment]
You're right. I think there will be no problem.

I'll try to make a simple PR to fix this problem.

**Comment by lhstrh** [comment]
Fixed in #144.
