### ISSUE TITLE
Add a Dependabot to auto update dependencies and such

### ISSUE THREAD

**Issue by axmmisaka** [lf-lang/reactor-ts#145]

**Comment by lhstrh** [comment]
How do we add these?

**Comment by axmmisaka** [comment]
I think it's here: 
![image](https://github.com/lf-lang/reactor-ts/assets/6500159/b53d4630-0d04-4de0-93ec-1bee4f444206)

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates
