### ISSUE TITLE
Possibilities of eliminating binding workarounds

### ISSUE THREAD

**Issue by axmmisaka** [lf-lang/reactor-ts#159]
As I address https://github.com/lf-lang/reactor-ts/pull/158 it appears that there are some nontrivial use of this alias.

https://github.com/lf-lang/reactor-ts/blob/6d7c64b47dcb08485b4caa3f69e7750ede8fa34b/src/core/federation.ts#L359
https://github.com/lf-lang/reactor-ts/blob/6d7c64b47dcb08485b4caa3f69e7750ede8fa34b/src/benchmark/FacilityLocation.ts#L507

I'm a bit curious are there any reason other than scoping that let to such design?

This should be closed as we merge #158 - that is, either we remove these aliases, or remove the rule.

**Comment by lhstrh** [comment]
It's a pattern to keep access to an "outer" `this` after it gets shadowed. Does eslint complain about it? Here is an explanation of the pattern: https://stackoverflow.com/questions/4886632/what-does-var-that-this-mean-in-javascript

**Comment by axmmisaka** [comment]
Yes - it's a rather old design pattern and is discouraged according to eslint (https://typescript-eslint.io/rules/no-this-alias/); it appears that arrow functions (or use `bind`) are encouraged as an alternative. I think this is some re-structuring we could do later.
Additionally, it appears that some of our design which utilised `that` does not suffer from scoping issue at all (if no now closure is created there shouldn't be any scoping issue, iiuc). 

This is what ChatGPT told me......:

> In pre-ES6 JavaScript, it was common to assign `this` to a separate variable, often named `that`, `self`, or `me`, as a workaround to maintain the correct context inside nested functions or callback functions. This was necessary because the inner functions would have their own `this` binding, which could differ from the desired context.
> 
> Here's an example of how the "this binding workaround" was used:
> 
> ```typescript
> function MyClass() {
>   var that = this;
> 
>   this.name = 'MyClass';
> 
>   setTimeout(function() {
>     console.log(that.name); // Accessing the correct context using `that`
>   }, 1000);
> }
> ```
> 
> In this example, `that` is assigned the value of `this`, providing a reference to the desired context within the nested `setTimeout` callback.
> 
> However, with the introduction of arrow functions in ES6, the need for such assignments and workarounds is significantly reduced. Arrow functions do not have their own `this` binding; instead, they inherit the `this` value from the surrounding lexical scope.
> 
> Here's an equivalent version of the previous example using an arrow function:
> 
> ```typescript
> class MyClass {
>   name = 'MyClass';
> 
>   someMethod() {
>     setTimeout(() => {
>       console.log(this.name); // Automatically captures the correct context using lexical `this`
>     }, 1000);
>   }
> }
> ```
> 
> In this updated code, the arrow function used as the `setTimeout` callback can directly access the correct `this` context from the enclosing `someMethod` method. There's no need to assign `this` to a separate variable or use the "this binding workaround."
> 
> By using arrow functions, you can write more concise and readable code while maintaining the desired `this` context. Arrow functions capture the `this` value lexically, making it easier to access the correct context without explicit assignments.
> 
> However, it's important to note that there may still be scenarios where regular functions or other techniques like `bind`, `call`, or `apply` are necessary to manage the `this` context, especially when dealing with dynamically changing contexts or using third-party libraries that rely on function binding.
> 
> Feel free to ask if you have any further questions or need clarification on this topic!

**Comment by lhstrh** [comment]
Jep. Lambda's to the rescue :rocket:

On a related note, the code base currently has a distinctive Java-like, inheritance-heavy feel to it. This is probably my fault, and I would not mind following what are considered today's best practices.

One unusual thing that might not be obvious (either to eslint or to you), is that I've gone to considerable length to achieve forms of data hiding and type inference by playing some tricks. I would encourage you to make many commits so that we can see where things break, if they do break. I'll help address failures...

**Comment by axmmisaka** [comment]
I'll make sure code doesn't break, then try to make eslint happy......
