### ISSUE TITLE
Stop using ULog, migrate to loglevel or winston

### ISSUE THREAD

**Issue by axmmisaka** [lf-lang/reactor-ts#228]
ULog is last maintained 3 years ago, has rather poor documentation, very few people use it, and it doesn't have type info published on NPM. We should consider switching to a more modern and well-maintained log library, such as loglevel or winston.

Lucky for us we already have a logger wrapper, so phasing ULog out shouldn't take too much effort.

**Comment by lhstrh** [comment]
I agree, it ended up being a poor choice. The main attraction was that is was lightweight. We need to have a logger that doesn't waste many CPU cycles when log levels are low or logging has been disabled. What library do you propose to replace it with?

**Comment by axmmisaka** [comment]
I'll give https://github.com/pinojs/pino a shot as we don't need fancy networking functionality and it claims to have very low overhead...... If they consume more CPU cycles we should sue them for inaccuracies ;p
