### ISSUE TITLE
Remove aliases in time.ts

### ISSUE THREAD

**Issue by axmmisaka** [lf-lang/reactor-ts#229]
In `time.ts` we have time units and their aliases. 

This is the main reason why https://github.com/lf-lang/reactor-ts/pull/227 is failing linting because of a newly introduced linting rule.

In the code generator, the canonical name of time units are all singular. Plural forms are all aliases and (I believe) won't be included in the generated code.

We should remove the aliases to make eslint happy and to improve code quality.

https://github.com/lf-lang/reactor-ts/blob/b81e1ce9214835d8e3197af1f2d4b4c7b9cac927/src/core/time.ts#L11-L25

https://github.com/lf-lang/lingua-franca/blob/4dbd9f822d1c769f37de179d00deb87aeff5f6d4/core/src/main/java/org/lflang/TimeUnit.java#L40-L58

**Comment by lhstrh** [comment]
:+1:
