### ISSUE TITLE
Redesign how command-line-args and command-line-usage modules work

### ISSUE THREAD

**Issue by hokeun** [lf-lang/reactor-ts#86]
For example, cli.ts has

```
import commandLineArgs from 'command-line-args';
import commandLineUsage from 'command-line-usage';
```

which are not directly used inside cli.ts, but maybe in the generated code.
We could design this better.

@lhstrh Please feel free to edit the description here. :)

**Comment by lhstrh** [comment]
I agree. These import statements should be included in the generated code instead. That will also remove a dependency from this project...

@axmmisaka are you interested in picking this up? Should be an easy fix...

**Comment by axmmisaka** [comment]
What I tried to do is use this (https://github.com/lf-lang/vscode-lingua-franca/blob/main/tslint.json), convert it to ESLint config and run ESLint on the whole repo. After the exam tomorrow I think it might be a good idea to fix all of them and fix things broken by the linter

**Comment by lhstrh** [comment]
@axmmisaka, there is a pending PR #83 that uses Prettier instead of ESLint.

**Comment by lhstrh** [comment]
Also, this issue isn't really about formatting or linting but about removing a dependency from `reactor-ts` that should be introduced by the code generator.

**Comment by lhstrh** [comment]
> > @axmmisaka, there is a pending PR #83 that uses Prettier instead of ESLint.
> 
> If I recall correctly, ESLint and Prettier do different things
> 
True. I think it's a good idea to also set up ESLint and fix those problems, but let's discuss that in a separate issue/PR.

**Comment by axmmisaka** [comment]
> > > @axmmisaka, there is a pending PR #83 that uses Prettier instead of ESLint.
> > 
> > 
> > If I recall correctly, ESLint and Prettier do different things
> 
> True. I think it's a good idea to also set up ESLint and fix those problems, but let's discuss that in a separate issue/PR.

I'm a bit curious, though, what this issue is trying to address - it doesn't appear to be a design problem if it's not used anywhere (in contrast, it could potentially be a design problem if, say, it's used somewhere, but solely as a placeholder)
